### ISSUE TITLE
Authorに設定する情報をください

### ISSUE THREAD

**Issue by igameta** [TDU-SCSIRT/tdu-scsirt.github.io#13]
設定ファイルの例
```
name = "igameta"
image = "https://avatars.githubusercontent.com/u/29007466?v=4"
bio = "パソカタなんでもやさん。このウェブサイトの管理者らしい。"
social = [
    {"twitter" = "https://twitter.com/igameta"},
    {"github" = "https://github.com/igameta"},
]
```

コピペ用
```
name = ""
image = ""
bio = ""
social = []
```

socialで設定できるのは、
- GitHub
- Twitter
- Keybase
- linkedin
- reddit
- medium
``scsirt/themes/blowfish/assets/icons``か``scsirt/assets/icons``にあるsvgなら全て設定できる
キーにsvgのファイル名(拡張子なし)を指定すると設定できる

**Comment by igameta** [comment]
アイコン画像は無ければ無しでOK 適当なアイコンを用意します
bioは思いつかなかったら適当に書きます
socialはお好みで

**Comment by jinnosukeKato** [comment]
```toml
name = "加藤仁之助"
image = ""
bio = "天文学研究部部長 CSIRTは副業"
social = [
    {"twitter" = "https://twitter.com/jinnosukekato"},
    {"github" = "https://github.com/jinnosukekato"},
]
```
